Initial ExRTCScore implementation
jellyfish-dev/ex_rtcscore pull request #1
Opened 2024-03-15 17:27 UTC by sgfn

Will update the docs and add more tests, but the main part of code is ready for review

2024-03-18 15:56 UTC, roznawsk requested changes
I have a general note regarding the default values in the `Config`.
If I understand correctly, sometimes there are values missing in the webrtc-internals report so we just use the defaults.

So, if for some reason we don't receive width and height of the frame and receive low layer (less than 640 x 480) than our score is inflated relative to the true value.
Similarily, if we received layer high (more than 640x480) our score would be deflated relative to the true value.
We assume that this happens relatively rarely and we are okay with this?

2024-03-18 15:56 UTC, roznawsk commented on lib/ex_rtcscore/config/audio.ex
> +  TODO rewriteme
Remove TODO if the doc is finished.

2024-03-18 15:56 UTC, roznawsk commented on lib/ex_rtcscore/config/audio.ex
> +  @spec normalise(t()) :: t()
Imo this would be more explanatory if we named this function `fill_defaults` or `put_defaults_if_nil`.

2024-03-18 15:56 UTC, roznawsk commented on lib/ex_rtcscore/config/video.ex
> +  TODO rewriteme
Remove TODO if the doc is finished.

2024-03-18 15:56 UTC, roznawsk commented on lib/ex_rtcscore/config/video.ex
> +  @spec normalise(t()) :: t()
Same as with audio.

2024-03-18 15:56 UTC, roznawsk commented on lib/ex_rtcscore/stat.ex
> +  @spec normalise(t()) :: t()
Imo this would be more explanatory if we named this function fillDefaults or something similar.

2024-03-18 15:56 UTC, roznawsk commented on lib/ex_rtcscore/stat.ex
> +  TODO rewriteme
Remove TODO if the doc is finished.

2024-03-18 15:56 UTC, roznawsk commented on lib/ex_rtcscore/webrtc_internals/track_report.ex
> +          end_time: String.t(),
I think it would be nice to have those values as Elixir time.

2024-03-18 15:56 UTC, roznawsk commented on lib/ex_rtcscore/stat.ex
> +    buffer_delay: 50
Why this particular values?

2024-03-18 15:56 UTC, roznawsk commented on lib/ex_rtcscore/webrtc_internals/track_report.ex
> +          end_time: String.t(),
From what I see they are already datetime type in fact, so just changing typecspec would suffice?

2024-03-18 15:56 UTC, roznawsk commented on lib/ex_rtcscore/webrtc_internals/parser.ex
There is a lot of parsing and nested loops here. I just assume this is OK.

2024-03-18 15:56 UTC, roznawsk commented on lib/ex_rtcscore/webrtc_internals.ex
> +         {kind, report} -> {kind, do_score(report, score_ctx)}
```suggestion
         {kind, track_report} -> {kind, score_track_report(track_report, score_ctx)}
```

2024-03-18 15:56 UTC, roznawsk commented on lib/ex_rtcscore/webrtc_internals.ex
> +  defp do_score(report, score_ctx) do
It just made me confused for a moment
```suggestion
  defp score_track_report(report, score_ctx) do
```

2024-03-20 11:49 UTC, sgfn commented
> So, if for some reason we don't receive width and height of the frame and receive low layer (less than 640 x 480) than our score is inflated relative to the true value. Similarily, if we received layer high (more than 640x480) our score would be deflated relative to the true value. We assume that this happens relatively rarely and we are okay with this?

This was copied over from the golang implementation. I had my doubts about this, too -- and since your points are valid, I think it'd be best to get rid of all default values and let the users provide them in `score_ctx` only, if they so desire.

2024-03-20 11:49 UTC, sgfn commented on lib/ex_rtcscore/stat.ex
> +    buffer_delay: 50
Again, copied over from golang implementation -- will remove them

2024-03-22 13:29 UTC, roznawsk approved these changes

2024-03-22 14:11 UTC, merged